config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  
  get 'offers/:id/edit', to: 'offers#edit'
  post 'offers/:id/', to: 'offers#update'
  put 'offers/:id/', to: 'offers#update'
  
  get 'profiles/:id/edit', to: 'profiles#edit'
  post 'profiles/:id/', to: 'profiles#update'
  put 'profiles/:id/', to: 'profiles#update'
  
  resources :offers, only: [:show, :new, :create, :edit, :update] do
    member do
      get :cities
      get :choices
    end
  end

  resources :users, only: [:index, :show, :new, :create]
  resources :offers, only: [:edit, :update, :destroy]
  resources :profiles, only: [:edit, :update, :destroy]
  resources :messages, only: [:create]
  resources :entries, only: [:index, :show, :create]
  resources :rooms, only: [:index, :show, :create]
end

app/models/room.rb
class Room < ApplicationRecord

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
    before_action :require_user_logged_in

    def index
        @entries = Entry.where(user_id: current_user.id)
    end
    
    def create
    end

    def show
        @room = Room.find(params[:id])
        if Entry.where(:user_id => current_user.id, :room_id => @room.id).present?
            @messages = @room.messages
            @message = Message.new
            @entries = @room.entries
        else
            redirect_back(fallback_location: root_path)
        end
    end
end

app/views/rooms/index.html.erb
<h1>メッセージ一覧</h1>

<table class="table">
    <% @entries.each do |e| %>
        <tr>
            <% @room = Room.find(e.room_id) %>
            <td><%= link_to @room.name, room_path(@room) %>からのメッセージ</td>
        </tr>
    <% end %>
</table>

app/views/rooms/show.html.erb
<h1 class="mb-2"><%= @room.name %>とのメッセージ</h1>

<table class="table">
    <% @messages.each do |m| %>
        <tr>
            <td>
        <div class="message">
            <div class="row mb-1 justify-content-between">
                <h5><%= m.user.name %></h5>
                <span><%= m.created_at %></span>
            </div>
            <%= m.content %>
        </div>
            </td>
        </tr>
    <% end %>
</table>

    <%= form_with(model: @message, local: true) do |f| %>
      <%= f.text_area :content, size: "136x3" %>
      <%= f.hidden_field :room_id, :value => @room.id %>
      <br>
      <div class="float-right">
          <%= f.submit "送信する", class: 'btn btn-primary justify-content-end'%>
      </div>
    <% end %>
    
    <br>
    <%= link_to 'メッセージ一覧に戻る', rooms_path %>
</div>