config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  
  get 'offers/:id/edit', to: 'offers#edit'
  post 'offers/:id/', to: 'offers#update'
  put 'offers/:id/', to: 'offers#update'
  
  get 'profiles/:id/edit', to: 'profiles#edit'
  post 'profiles/:id/', to: 'profiles#update'
  put 'profiles/:id/', to: 'profiles#update'
  
  resources :offers, only: [:show, :new, :create, :edit, :update] do
    member do
      get :cities
      get :choices
    end
  end

  resources :users, only: [:index, :show, :new, :create]
  resources :offers, only: [:edit, :update, :destroy]
  resources :profiles, only: [:edit, :update, :destroy]
  resources :messages, only: [:create]
  resources :entries, only: [:index, :show, :create]
  resources :rooms, only: [:index, :show, :create]
end

app/models/offer.rb
class Offer < ApplicationRecord
  belongs_to :user

  validates :min_price, numericality: true
  validates :max_price, numericality: true
  validates :years, numericality: true
  validates :walking_time, numericality: true
  validates :min_size, numericality: true
  validates :is_family, inclusion: { in: [true, false]}
  validates :is_family, inclusion: { in: [true, false]}, default: false;

  has_many :offer_city_relation, dependent: :destroy
  has_many :cities, through: :offer_city_relation
  has_many :offer_choice_relation, dependent: :destroy
  has_many :choices, through: :offer_choice_relation
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  before_action :require_user_logged_in
  before_action :offer_params, only: [:update]
  
  def new
  end

  def create
  end

  def edit
    if (@offer = current_user.offer) == nil
      @offer = @user.build_offer
      @offer.save
    end
    
    p @offer
  end

  def update
    @offer = current_user.offer

    if @offer.update(offer_params)
      flash[:success] = 'オファー内容を編集しました。'
      redirect_to user_path(current_user.id)
    else
      flash.now[:danger] = 'オファー内容の編集に失敗しました。'
      render :edit
    end
  end

  def destroy
    @offer = current_user.offer
    
    @offer.destroy
    flash[:success] = 'オファーを終了しました。'
    redirect_to user_path(current_user.id)
  end
  
  private
  
  def offer_params
    p params
    params.require(:offer).permit(:min_price, :max_price, :years, :walking_time, :min_size, :is_family, :is_offered, city_ids: [], choice_ids: [])
  end
  
end

app/views/offers/_offer_button.html.erb
<% if current_user.id == @user.id %>
    <%# 自分自身のとき編集ボタンを表示する %>
    <%= link_to 'オファーを登録/編集する', edit_offer_path(@offer.id), class: 'btn btn-primary mr-2' %> 
    <% if @offer.is_offered == true %>
        <%= link_to 'オファーを終了する', @offer, method: :delete, data: { confirm: '本当に終了してもよろしいですか？' }, class: 'btn btn-danger mr-2' %> 
    <% end %>

<% elsif current_user.is_estate == true %>
    <%# 自分が不動産ユーザーの時は、Entryを新規作成してメッセージを開始する %>
    <%= form_with(model: @entry, local: true) do |f| %>
        <%= f.hidden_field :estate_user_id, :value => current_user.id %>
        <%= f.hidden_field :normal_user_id, :value => @user.id %>
        <%= f.submit 'メッセージを送る', class: 'btn btn-primary' %>
    <% end %>
<% end %>

app/views/offers/_offer_view.html.erb
<table class="table" id="information-view">
    <tr>
        <th>オファー状況</th>
        <td>
            <% if @offer.is_offered %>オファー受付中
            <% else %>オファー受付停止
            <% end %>
        </td>
    </tr>
    <tr>
        <th>希望地域</th>
        <td>
            <% @offer.cities.each do |c| %>
                <span style="margin-right: 5px"><%= c.name %></span>
            <% end %>
        </td>
    </tr>
    <tr>
        <th>家賃</th>
        <td><%= @offer.min_price.to_s %>円 〜 <%= @user.offer.max_price.to_s %>円</td>
    </tr>
    <tr>
        <th>築年数</th>
        <td><%= @offer.years.to_s %>年以内</td>
    </tr>
    <tr>
        <th>最寄駅徒歩</th>
        <td><%= @offer.walking_time.to_s %>分以内</td>
    </tr>
    <tr>
        <th>専有面積</th>
        <td><%= @offer.min_size.to_s %>平米以上</td>
    </tr>
    <tr>
        <th>家族構成</th>
        <td>
            <% if @offer.is_family %>ファミリー
            <% else %>単身
            <% end %>
        </td>
    </tr>
    <tr>
        <th>こだわり条件</th>
        <td>
            <% @offer.choices.each do |c| %>
                <div><%= c.content %></div>
            <% end %>
        </td>
    </tr>
</table>

app/views/offers/edit.html.erb
<h1>オファー内容を編集する</h1>

<%= form_with(model: @offer, local: true) do |f| %>
    <%= f.hidden_field :user_id, :value => current_user.id %>
    <%= f.hidden_field :is_offered, :value => true %>
    <table class="table" id="information-view">

        <tr>
            <th>希望地域</th>
            <td>
                <%= f.collection_check_boxes :city_ids, City.all, :id, :name do |b|%>
                    <span style="margin-right: 5px"><%= b.check_box + b.label %></span>
                <% end %>
            </td>
        </tr>
        <tr>
            <th>家賃</th>
            <td><%= f.number_field :min_price %>円 ~ <%= f.number_field :max_price %>円</td>
        </tr>
        <tr>
            <th>築年数</th>
            <td><%= f.number_field :years %>年以内</td>
        </tr>
        <tr>
            <th>最寄駅徒歩</th>
            <td><%= f.number_field :walking_time %>分以内</td>
        </tr>
        <tr>
            <th>専有面積</th>
            <td><%= f.number_field :min_size %>平米以上</td>
        </tr>
        <tr>
            <th>家族構成</th>
            <td>
                <label style="margin-right: 10px"><%= f.radio_button :is_family, :false %>単身</label>
                <label><%= f.radio_button :is_family, :true %>ファミリー</label>
            </td>
        </tr>
        <tr>
            <th>こだわり条件</th>
            <td>
                <%= f.collection_check_boxes :choice_ids, Choice.all, :id, :content do |b| %>
                    <div><%= b.check_box + b.label %></div>
                <% end %>
            </td>
        </tr>
    </table>
    <div class="row justify-content-center">
        <%= f.submit '編集', class: 'btn btn-primary'%>
    </div>
<% end %>

app/views/offers/new.html.erb
<h1>オファー内容を登録する</h1>

<%= form_with(model: @offer, local: true) do |f| %>
    <table class="table">
        <tr>
            <td style="width: 20%">希望地域</td>
            <td>
                <%= f.collection_check_boxes :city_ids, City.all, :id, :name do |b| %>
                    <span style="margin-right: 5px"><%= b.check_box + b.label %></span>
                <% end %>
            </td>
        </tr>
        <tr>
            <td>家賃</td>
            <td><%= f.number_field :min_price %>円 ~ <%= f.number_field :max_price %>円</td>
        </tr>
        <tr>
            <td>築年数</td>
            <td><%= f.number_field :years %>年以内</td>
        </tr>
        <tr>
            <td>駅徒歩</td>
            <td><%= f.number_field :walking_time %>分以内</td>
        </tr>
        <tr>
            <td>専有面積</td>
            <td><%= f.number_field :min_size %>平米以上</td>
        </tr>
        <tr>
            <td>家族構成</td>
            <td>
                <label style="margin-right: 10px"><%= f.radio_button :is_family, false %>単身</label>
                <label><%= f.radio_button :is_family, true %>ファミリー</label>
            </td>
        </tr>
        <tr>
            <td>こだわり条件</td>
            <td>
                <%= f.collection_check_boxes :choice_ids, Choice.all, :id, :content do |b| %>
                    <div><%= b.check_box + b.label %></div>
                <% end %>
            </td>
        </tr>
    </table>
    
    <div class="row justify-content-center">
        <%= f.submit '登録', class: 'btn btn-primary'%>
    </div>
<% end %>

app/views/offers/update.html.erb
<h1>Offers#update</h1>
<p>Find me in app/views/offers/update.html.erb</p>