config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  
  get 'offers/:id/edit', to: 'offers#edit'
  post 'offers/:id/', to: 'offers#update'
  put 'offers/:id/', to: 'offers#update'
  
  get 'profiles/:id/edit', to: 'profiles#edit'
  post 'profiles/:id/', to: 'profiles#update'
  put 'profiles/:id/', to: 'profiles#update'
  
  resources :offers, only: [:show, :new, :create, :edit, :update] do
    member do
      get :cities
      get :choices
    end
  end

  resources :users, only: [:index, :show, :new, :create]
  resources :offers, only: [:edit, :update, :destroy]
  resources :profiles, only: [:edit, :update, :destroy]
  resources :messages, only: [:create]
  resources :entries, only: [:index, :show, :create]
  resources :rooms, only: [:index, :show, :create]
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="mb-4">
    <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
        <a class="navbar-brand" href="/">EstateMatching</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
            <span class="navbar-toggler-icon"></span>
        </button>
        
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto"></ul>
            <ul class="navbar-nav">
                <% if logged_in? %>
                    <% if current_user.is_estate == true %>
                        <li class="nav-item"><%= link_to '顧客一覧', users_path, class: 'nav-link' %></li>
                    <% end %>
                    <li class="nav-item"><%= link_to 'メッセージ', entries_path, class: 'nav-link' %></li>
                    <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown"><%= current_user.name %></a>
                    <ul class="dropdown-menu dropdown-menu-right">
                        <li class="dropdown-item"><%= link_to 'マイページ', user_path(current_user) %></li>
                        <li class="dropdown-driver"></li>
                        <li class="dropdown-item"><%= link_to 'ログアウト', logout_path, method: :delete %></li>
                    </ul>
                <% else %>
                    <li class="nav-item"><%= link_to '新規登録', signup_path, class: 'nav-link' %></li>
                    <li class="nav-item"><%= link_to 'ログイン', login_path, class: 'nav-link' %></li>
                <% end %>
            </ul>
        </div>
    </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>EstateMatching</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    
    <div class="container">
      <%= render 'layouts/flash_messages' %>
      
    <%= yield %>
    </div>
  </body>
</html>